### ISSUE TITLE
Error in `colnames<-`(`*tmp*`, value = c("x", "y", "similarity")) :    'names' attribute [3] must be the same length as the vector [0]

### ISSUE THREAD

**Issue by Ninoninoninonino** [kasperwelbers/newsflow#1]
Awesome tool. I used to be able to run _delete.duplicates_ but now I'm getting problems.

Command and parameters look as follows:

`delete.duplicates(dtm.tdm, 
                                     meta, 
                                     hour.window = c(-1,1),
                                     measure = "cosine", 
                                     similarity = 1, 
                                     keep = "first", 
                                     tf.idf = FALSE)
`

I get the following error code:
```
Indexing articles by date/time
Comparing documents
Matching document meta
Error in `colnames<-`(`*tmp*`, value = c("x", "y", "similarity")) : 
  'names' attribute [3] must be the same length as the vector [0]
```
My meta file looks like this:

` 
head(meta)
Year                date              source                            language           document_id
1 2014 2010-10-31 01:30:11 www.wbcsdcement.org  ENGLISH           1
2 2014 2010-10-31 01:30:11 www.wbcsdcement.org  ENGLISH           2
3 2014 2010-10-31 01:30:11 www.wbcsdcement.org  ENGLISH           3
4 2014 2010-10-31 01:30:11 www.wbcsdcement.org  ENGLISH           4
5 2014 2010-10-31 01:30:11 www.wbcsdcement.org  ENGLISH           5
6 2014 2010-10-31 01:30:11 www.wbcsdcement.org  ENGLISH           6
> tail(meta)
     Year                date              source                                   language       document_id
6094 2016 2010-10-31 01:30:13 www.wbcsdcement.org  ENGLISH        6094
6095 2016 2010-10-31 01:30:13 www.wbcsdcement.org  ENGLISH        6095
6096 2016 2010-10-31 01:30:13 www.wbcsdcement.org  ENGLISH        6096
6097 2016 2010-10-31 01:30:13 www.wbcsdcement.org  ENGLISH        6097
6098 2016 2010-10-31 01:30:13 www.wbcsdcement.org  ENGLISH        6098
6099 2016 2010-10-31 01:30:13 www.wbcsdcement.org  ENGLISH        6099`

My DTM also has 6099 rows:

`> tail(rownames(dtm.tdm))
[1] "6094" "6095" "6096" "6097" "6098" "6099"`

How should I interpret the error message?

**Comment by kasperwelbers** [comment]
Sorry for replying so late, I somehow missed the notification of your issue!

It seems that the error occurred because there were zero duplicates.  My bad: this didn't surface in my zero duplicate tests, because there I only had zero duplicates after filters further down the line.

Thanks for notifying this, I have fixed the code so that it notes that no duplicates were found, and returns the full data as it should. (update only in the development version; we'll update the CRAN version after we implement compatibility with another package we're working on)
