### ISSUE TITLE
Error in seq.int(0, to0 - from, by) : 'to' must be a finite number

### ISSUE THREAD

**Issue by phimeyer** [kasperwelbers/newsflow#3]
Dear Mr. Welbers,

I am trying to run the RNewsflow package on a huge data set which concerns both, court decisions and newspaper articles. 

I have constructed dfm (quanteda package) which contains a variable called "document_id" and one which called "date". The date variable is in POSIXlt format and includes date and time (e.g. "2019-01-07 00:10:00"

The error occurs when running the term.day.dist function
`tdd <-  term.day.dist(dtm, dtm@docvars)`

as well as when running the newsflow.compare function

`g <-  RNewsflow::newsflow.compare(dtm, dtm@docvars)`

Thank you for your help. 

All the best, 

Philipp

*Edit*: It works well when transforming the quanteda object to a tm object.

**Comment by kasperwelbers** [comment]
Dear Philipp,

Sorry for the late response. Are you using the CRAN or Github (development) version? I'm currently working on updating the code and recently replaced the entire backend, but haven't gotten around to term.day.dist() yet. Hopefully this week.

Best,
Kasper

**Comment by kasperwelbers** [comment]
Hi Philipp,

I took a while to get to it and to replicate the error. It turns out it was caused (at least in my case) by NA values in the date. 

Best,
Kasper

**Comment by kasperwelbers** [comment]
oh right!
fix is that documents without date (NA) are now ignored for the term.day.dist calculation
