### ISSUE TITLE
Problem with newsflow_compare - date_var "ym" is not a valid column in quanteda::docvars(dtm)

### ISSUE THREAD

**Issue by CCristancho** [kasperwelbers/newsflow#7]
Hi,
I'm trying to get a network of document similarities using this code:

newsflow_compare(mydfm, date_var='ym',
+                      hour_window = c(24,120), 
+                      min_similarity = .8)

But I get this:
Error in newsflow_compare(mydfm, date_var = "ym", hour_window = c(24,  : 
  date_var "ym" is not a valid column in quanteda::docvars(dtm)

I appreciate if you can point me to my problem as I believe I am using the right format for the date column:
class(docvars(mydfm)$ym)
[1] "POSIXct" "POSIXt" 

head(docvars(mydfm)$ym)
[1] "1993-09-01 CEST" "1993-09-01 CEST" "1994-02-01 CET"  "1998-02-01 CET"  "1998-02-01 CET" 

I also tried creating the dfm with corpustools and I run into the same issue.
Thanks. Best,

**Comment by kasperwelbers** [comment]
Hi @CCristancho,

You're not doing anything wrong, this one's entirely on me. I did some last minute refactoring, and apparently made a silly mistake that wasn't caught in the unit tests. 

I'll fix this later today on the development version (and I have a CRAN update plannen in a week or so). For now, the workaround is to call the date column "date". 

Best,
Kasper

**Comment by CCristancho** [comment]
Thanks! Looking forward to the update.
Best,

**Comment by kasperwelbers** [comment]
Should be fixed now (in the development version).

Thanks for spotting this!
